# Generated by Django 2.2.5 on 2019-09-27 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('mark', models.IntegerField(verbose_name='Оценка')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=100, verbose_name='Название платформы')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефонный номер')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('surname', models.CharField(max_length=60, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=60, verbose_name='Отчество')),
                ('bio', models.TextField(max_length=1000, verbose_name='Биография')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerReviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('review', models.CharField(max_length=250, verbose_name='Отзыв')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('mark_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Marks')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Platform')),
                ('voluenteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformReviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('review', models.CharField(max_length=250, verbose_name='Отзыв')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('mark_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Marks')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Platform')),
                ('voluenteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID новости')),
                ('content', models.TextField(max_length=3000, verbose_name='Содержание новости')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Platform')),
                ('voluenteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание события')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('surname', models.CharField(max_length=60, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=60, verbose_name='Отчество')),
                ('position', models.CharField(max_length=60, verbose_name='Должность')),
                ('tel', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('block_reason', models.TextField(max_length=1000, verbose_name='Причина блокировки')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Platform')),
                ('voluenteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museer.Volunteer')),
            ],
        ),
    ]
