# Generated by Django 2.2.5 on 2019-09-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='blacklist',
            old_name='voluenteer_id',
            new_name='voluenteer',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='eventsubscription',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='eventsubscription',
            old_name='voluenteer_id',
            new_name='voluenteer',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='platformreviews',
            old_name='mark_id',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='platformreviews',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='platformreviews',
            old_name='voluenteer_id',
            new_name='voluenteer',
        ),
        migrations.RenameField(
            model_name='volunteerreviews',
            old_name='mark_id',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='volunteerreviews',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='volunteerreviews',
            old_name='voluenteer_id',
            new_name='voluenteer',
        ),
    ]
